import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Service - SocialFly',
  description: 'SocialFly terms of service and conditions of use.',
  other: {
    'tiktok-developers-site-verification': '86ydRRIW34KPd9wLqgR2TAYV80n5CMf7',
  },
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border/50">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-3">
            <div className="flex items-center justify-center w-9 h-9 rounded-xl bg-primary text-primary-foreground font-bold text-sm">
              S
            </div>
            <span className="font-semibold text-lg tracking-tight text-foreground">SocialFly</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold text-foreground mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-12">Last updated: March 25, 2026</p>

        <div className="prose prose-invert max-w-none space-y-8 text-muted-foreground">
          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using SocialFly (&quot;the Service&quot;), operated by DropFly Inc. (&quot;we&quot;, &quot;us&quot;, &quot;our&quot;),
              you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              SocialFly is an AI-powered social media management platform that helps users create, schedule,
              and publish content across social media platforms including Instagram, Facebook, TikTok, and LinkedIn.
              The Service uses artificial intelligence to generate text, images, and video content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. Account Registration</h2>
            <p>
              You must provide accurate, complete, and current information when creating an account.
              You are responsible for maintaining the security of your account credentials and for all
              activities that occur under your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. User Content</h2>
            <p>
              You retain ownership of content you create or upload through the Service. By using the Service,
              you grant us a limited license to process, store, and transmit your content as necessary to
              provide the Service, including publishing to third-party platforms you authorize.
            </p>
            <p className="mt-3">
              You are solely responsible for the content you publish through the Service and must ensure it
              complies with applicable laws and the terms of service of each social media platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. AI-Generated Content</h2>
            <p>
              Content generated by our AI tools is provided as suggestions. You are responsible for reviewing,
              editing, and approving all content before it is published. We do not guarantee the accuracy,
              appropriateness, or legality of AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Third-Party Platform Integration</h2>
            <p>
              The Service integrates with third-party social media platforms (Instagram, Facebook, TikTok, LinkedIn, etc.).
              Your use of these platforms is subject to their respective terms of service. We are not responsible
              for the availability, policies, or actions of third-party platforms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Prohibited Uses</h2>
            <p>You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Violate any applicable laws or regulations</li>
              <li>Publish spam, misleading, or deceptive content</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Distribute malware or harmful content</li>
              <li>Attempt to gain unauthorized access to the Service or its systems</li>
              <li>Use the Service for any unlawful or unauthorized purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. To the maximum extent permitted
              by law, DropFly Inc. shall not be liable for any indirect, incidental, special, consequential, or
              punitive damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Termination</h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at any time for violation
              of these terms or for any other reason at our discretion. Upon termination, your right to use
              the Service ceases immediately.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. Continued use of the Service after changes
              constitutes acceptance of the updated terms. We will notify users of material changes
              via email or through the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Contact</h2>
            <p>
              For questions about these Terms of Service, contact us at{' '}
              <a href="mailto:support@socialfly.io" className="text-primary hover:underline">support@socialfly.io</a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
